name: Update CSV

on:
  repository_dispatch:
    types: [update_csv]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update CSV
        run: |
          echo "${{ github.event.client_payload.csv_content }}" > data.csv

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.csv
          git commit -m "🔄 update csv via GitHub Actions"
          git push
