name: Update CSV File

on:
  repository_dispatch:
    types: [update-csv]

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode base64 CSV and save to file
      run: |
        echo "${{ github.event.client_payload.csv_base64 }}" | base64 -d > SMTDATA.csv

    - name: Commit and push CSV
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add SMTDATA.csv
        git commit -m "📦 Update CSV via Actions" || echo "No changes"
        git push
