name: Update CSV

on:
  repository_dispatch:
    types: [update_csv]

jobs:
  update-csv-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode base64 and write CSV file
        run: |
          echo "${{ github.event.client_payload.csv_content_base64 }}" | base64 --decode > SMTDATA.csv

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add SMTDATA.csv
          git commit -m "🔄 Update CSV via GitHub Actions"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
