name: Update CSV

on:
  repository_dispatch:
    types: [update_csv]

jobs:
  update-csv-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update CSV file
        run: |
          echo "${{ github.event.client_payload.csv_content }}" > SMTDATA.csv

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add SMTDATA.csv
          git commit -m "Update CSV via GitHub Actions"
          git push
