name: Update CSV

on:
  repository_dispatch:
    types: [update_csv]

jobs:
  update-csv-file:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Save CSV content to file
        run: |
          echo "${{ github.event.client_payload.csv_content }}" > SMTDATA.csv

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add SMTDATA.csv
          git commit -m "Update CSV via GitHub Actions"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
