name: Update SMTDATA.csv

on:
  repository_dispatch:
    types: [update_csv]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Decode CSV and save
      run: |
        echo "${{ github.event.client_payload.csv_base64 }}" | base64 -d > SMTDATA.csv

    - name: Commit and push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        git add SMTDATA.csv
        git commit -m "อัปเดต CSV อัตโนมัติ"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
